#!/usr/bin/env bash

EXE_USER=root

user=`whoami`
if [ $user != $EXE_USER ]; then
    echo "[Error] You need to run it on the '${EXE_USER}' user."
    exit
fi

LANG=en
NODE=${HOSTNAME}
REPOSITORY=""

if [ ! -f ~/.chef-host/chef-host.conf ]; then
    echo "[Error] Not found ~/.chef-host/chef-host.conf"
    exit
fi

. ~/.chef-host/chef-host.conf

repodir=~/.chef-host/repo

if [ -z "$REPOSITORY" ]; then
    echo "[Error] You need to set repository url."
    exit
fi

# Initialize chef repository from git
if [ ! -e  $repodir/.git ]; then
    git clone $REPOSITORY $repodir
fi

# Update chef reopository using git pull.
cd $repodir
git pull

sudo /opt/chef/embedded/bin/berks --path cookbooks

nodefile="$repodir/nodes/${NODE}.json"
echo "sudo chef-solo -c ${repodir}/config/solo.rb -j ${nodefile}"
sudo chef-solo -c ${repodir}/config/solo.rb -j ${nodefile}







