#!/usr/bin/env bash

exeuser=root
user=`whoami`
if [ $user != $exeuser ]; then
    echo "[Error] You need to run by the '${exeuser}' user."
    exit
fi

LANG=en

node=${HOSTNAME}
repodir=/var/chef

# Initialize chef repository from git
if [ ! -e  $repodir/.git ]; then
    echo "[Error] You need to clone repository to ${repodir}"
    exit
fi

# Update chef reopository using git pull.
cd $repodir
git pull

# Prevent to load system wide ruby and gems.
unset GEM_HOME
unset GEM_PATH;

# Runs berks and chef-solo
/opt/chef/embedded/bin/berks --path cookbooks
chef-solo -c ${repodir}/config/solo.rb -j ${repodir}/nodes/${node}.json







