#!/usr/bin/env bash

exeuser=root
user=`whoami`
if [ $user != $exeuser ]; then
    echo "[Error] You need to run it on the '${exeuser}' user."
    exit
fi

LANG=en

node=${HOSTNAME}
repodir=/var/chef

# Initialize chef repository from git
if [ ! -e  $repodir/.git ]; then
    echo "[Error] You need to clone repository to ${repodir}"
    exit
fi

# Update chef reopository using git pull.
cd $repodir
git pull

sudo /opt/chef/embedded/bin/berks --path cookbooks

nodefile="$repodir/nodes/${node}.json"
echo "sudo chef-solo -c ${repodir}/config/solo.rb -j ${nodefile}"
sudo chef-solo -c ${repodir}/config/solo.rb -j ${nodefile}







